#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <mutex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

#include "TFile.h"
#include "TTree.h"
#include "Pythia8/Pythia.h"
#include "mcp_emitters.h"

namespace {
std::mutex gPrintMutex;

enum class GeometryId : int { ArgoNeuT = 0, TwoByTwo = 1 };
enum class StopMode : int { FixedEvents = 0, TargetAccepted = 1 };
enum class SpectraMode : int { All = 0, Accepted = 1, None = 2 };
enum class StopReason : int { CompletedFixedEvents = 0, ReachedTargetAccepted = 1, ReachedMaxEvents = 2, KinematicallyClosed = 3, PythiaInitFailure = 4 };

struct Options {
    int seed = 1, nThreads = 1, jobId = 0;
    long long legacyN = 1000, nEvents = -1, nAccepted = -1, maxEvents = -1;
    double mcpMass = 0.01;
    GeometryId geometry = GeometryId::TwoByTwo;
    std::string emitterName, outFile = "mcp_emitter.root", beamConfig = "beam.config", momentumConfig = "momentum.config", productionConfig = "";
    ProductionMode productionMode = ProductionMode::LightMesons;
    StopMode stopMode = StopMode::FixedEvents;
    SpectraMode spectraMode = SpectraMode::Accepted;
    int spectraPrescale = 1;
    bool quiet = false;
    bool printPythiaSettings = false;
};
struct Projection { bool passed=false; double x=0,y=0,z=0; };
struct SpectraRow { int event_index=0, seed=0, emitter_pdg=0, emitter_type=0, production_mode=0, geometry_id=0, mcp_pdg=0, mother_pdg=0, mother_index=-1, accepted=0, passed_geometry=0, mother_status=0, mother_is_primary_like=0, mother_mother_pdg=0, from_feeddown_flag=0; double mcp_mass_GeV=0, px_GeV=0, py_GeV=0, pz_GeV=0, E_GeV=0, p_GeV=0, theta_rad=0, theta_x_rad=0, theta_y_rad=0, eta=0, phi_rad=0, x_at_detector_m=0, y_at_detector_m=0, z_detector_m=0, mother_px_GeV=0, mother_py_GeV=0, mother_pz_GeV=0, mother_E_GeV=0, mother_p_GeV=0, mother_theta_rad=0; };
struct ThreadResult { int thread_id=0, seed=0; long long n_events_generated=0, n_pythia_next_failures=0, n_emitter_total=0, n_mcp_total=0, n_mcp_accepted=0, n_mcp_wrong_mother=0, n_mcp_no_mother=0; StopReason stop_reason=StopReason::CompletedFixedEvents; std::vector<SpectraRow> spectra; };
struct Progress { std::atomic<long long> events{0}, accepted{0}, failures{0}; std::atomic<int> done{0}; std::atomic<bool> stop{false}; std::atomic<int> reason{0}; };
std::string trim(std::string s){ auto b=s.find_first_not_of(" \t\r\n"); if(b==std::string::npos) return ""; auto e=s.find_last_not_of(" \t\r\n"); return s.substr(b,e-b+1);}
std::string cmd(const std::string&a,const std::string&b){return a+" = "+b;}
GeometryId parseGeometry(const std::string& g){ auto s=trim(g); if(s=="argoneut") return GeometryId::ArgoNeuT; if(s=="2x2"||s=="twobytwo") return GeometryId::TwoByTwo; throw std::runtime_error("Unknown geometry "+g);}
std::string geometryName(GeometryId g){return g==GeometryId::ArgoNeuT?"argoneut":"2x2";}
std::string emitterTypeName(EmitterType t){return t==EmitterType::Pseudoscalar?"pseudoscalar":(t==EmitterType::Vector?"vector":"dy_reserved");}
std::string stopReasonName(StopReason r){ switch(r){case StopReason::CompletedFixedEvents:return"completed_fixed_events";case StopReason::ReachedTargetAccepted:return"reached_target_accepted";case StopReason::ReachedMaxEvents:return"reached_max_events";case StopReason::KinematicallyClosed:return"kinematically_closed";case StopReason::PythiaInitFailure:return"pythia_init_failure";} return"unknown";}
Projection project(double px,double py,double pz,GeometryId geom){ Projection r; if(pz<=0) return r; if(geom==GeometryId::ArgoNeuT){r.z=1000.; r.x=px/pz*r.z; r.y=py/pz*r.z; r.passed=(r.x>=-0.24&&r.x<=0.24&&r.y>=-0.2&&r.y<=0.2); return r;} r.z=1040.; r.x=px/pz*r.z; r.y=py/pz*r.z; bool inbox=(r.x>=-0.65&&r.x<=-0.05)||(r.x>=0.05&&r.x<=0.65); r.passed=inbox&&r.y>=-0.7&&r.y<=0.7; return r; }
void configureMCP(Pythia8::Pythia& p,double m){ p.readString("ParticleDecays:limitTau0 = on"); p.readString("ParticleDecays:tau0Max = 1e12"); p.readString("1000222:new = chi chi~ 2 0 0 0 0"); std::ostringstream ss; ss<<std::fixed<<std::setprecision(9)<<m; p.readString(cmd("1000222:m0",ss.str())); p.readString("1000222:tau0 = 1e12"); p.readString("1000222:mayDecay = off"); }
void configureCommonBeamAndParticleSettings(Pythia8::Pythia& p,const Options& o,int seed){ p.readFile(o.beamConfig); p.readFile(o.momentumConfig); p.readString("Random:setSeed = on"); p.readString(cmd("Random:seed",std::to_string(seed))); p.readString("Next:numberCount = 0"); p.readString("Next:numberShowInfo = 0"); p.readString("Next:numberShowProcess = 0"); p.readString("Next:numberShowEvent = 0"); p.readString("Init:showProcesses = off"); p.readString("Init:showMultipartonInteractions = off"); p.readString("Init:showChangedSettings = off"); p.readString("Init:showChangedParticleData = off"); configureMCP(p,o.mcpMass); }
void configureLightMesonProduction(Pythia8::Pythia& p,const Options& o){ if(!o.productionConfig.empty()) p.readFile(o.productionConfig); }
void configureCharmoniumProduction(Pythia8::Pythia& p,const Options& o){ p.readString("SoftQCD:all = off"); p.readString("SoftQCD:nonDiffractive = off"); p.readString("SoftQCD:elastic = off"); p.readString("SoftQCD:singleDiffractive = off"); p.readString("SoftQCD:doubleDiffractive = off"); p.readString("SoftQCD:centralDiffractive = off"); p.readString("HardQCD:all = off"); p.readString("HardQCD:hardccbar = off"); p.readString("Charmonium:all = off"); const std::string cfg=o.productionConfig.empty()?"configs/charmonium.config":o.productionConfig; if(!cfg.empty() && std::filesystem::exists(cfg)){ p.readFile(cfg); } else { p.readString("HardQCD:hardccbar = on"); p.readString("Charmonium:all = on"); } }
void configureProduction(Pythia8::Pythia& p,const Options& o,int seed){ configureCommonBeamAndParticleSettings(p,o,seed); if(o.productionMode==ProductionMode::Charmonium) configureCharmoniumProduction(p,o); else configureLightMesonProduction(p,o); if(o.printPythiaSettings){ std::lock_guard<std::mutex> lock(gPrintMutex); std::cout<<"Changed Pythia settings before init (thread seed "<<seed<<"):\n"; p.settings.listChanged(); } }
void forceEmitter(Pythia8::Pythia& p,const EmitterConfig& e){ p.readString(std::to_string(e.pdg)+":onMode = off"); std::ostringstream ch; ch<<e.pdg<<":addChannel = 1 1.0 0"; if(e.type==EmitterType::Pseudoscalar) ch<<" 22"; ch<<" "<<kMcpPdg<<" "<<-kMcpPdg; p.readString(ch.str()); }
int motherIndex(const Pythia8::Event& ev,int i){ int m=ev[i].mother1(); if(m>0&&m<ev.size()) return m; m=ev[i].mother2(); if(m>0&&m<ev.size()) return m; return -1; }
bool keepSpectra(SpectraMode mode,int prescale,long long n,bool accepted){ if(mode==SpectraMode::None) return false; if(mode==SpectraMode::Accepted && !accepted) return false; return prescale<=1 || (n%prescale)==0; }
ThreadResult runThread(const Options& o,const EmitterConfig& e,int tid,long long targetEvents,Progress* prog){ ThreadResult r; r.thread_id=tid; r.seed=o.seed+tid; Pythia8::Pythia p("", false); configureProduction(p,o,r.seed); forceEmitter(p,e); if(!p.init()){ r.stop_reason=StopReason::PythiaInitFailure; prog->stop=true; prog->reason=(int)StopReason::PythiaInitFailure; prog->done++; return r; }
    while(!prog->stop){ if(o.stopMode==StopMode::FixedEvents && r.n_events_generated>=targetEvents) break; if(o.stopMode==StopMode::TargetAccepted && o.maxEvents>0 && prog->events>=o.maxEvents){ prog->stop=true; prog->reason=(int)StopReason::ReachedMaxEvents; break; } if(!p.next()){ r.n_pythia_next_failures++; prog->failures++; continue; } long long evGlobal=prog->events++; (void)evGlobal; r.n_events_generated++; int eventIndex=(int)(tid*1000000000LL + r.n_events_generated-1); for(int i=0;i<p.event.size();++i){ const auto& part=p.event[i]; if(part.id()==e.pdg) r.n_emitter_total++; if(std::abs(part.id())!=kMcpPdg) continue; r.n_mcp_total++; int mi=motherIndex(p.event,i); int mpdg=(mi>=0)?p.event[mi].id():0; if(mi<0) r.n_mcp_no_mother++; else if(mpdg!=e.pdg) r.n_mcp_wrong_mother++; Projection pr=project(part.px(),part.py(),part.pz(),o.geometry); if(pr.passed){ r.n_mcp_accepted++; long long a=++prog->accepted; if(o.stopMode==StopMode::TargetAccepted && o.nAccepted>0 && a>=o.nAccepted){ prog->stop=true; prog->reason=(int)StopReason::ReachedTargetAccepted; } } if(keepSpectra(o.spectraMode,o.spectraPrescale,r.n_mcp_total,pr.passed)){ SpectraRow s; s.event_index=eventIndex; s.seed=r.seed; s.mcp_mass_GeV=o.mcpMass; s.emitter_pdg=e.pdg; s.emitter_type=(int)e.type; s.production_mode=(int)o.productionMode; s.geometry_id=(int)o.geometry; s.mcp_pdg=part.id(); s.mother_pdg=mpdg; s.mother_index=mi; s.accepted=pr.passed; s.passed_geometry=pr.passed; s.px_GeV=part.px(); s.py_GeV=part.py(); s.pz_GeV=part.pz(); s.E_GeV=part.e(); s.p_GeV=part.pAbs(); s.theta_rad=part.theta(); s.theta_x_rad=(part.pz()!=0?part.px()/part.pz():0); s.theta_y_rad=(part.pz()!=0?part.py()/part.pz():0); s.eta=part.eta(); s.phi_rad=part.phi(); s.x_at_detector_m=pr.x; s.y_at_detector_m=pr.y; s.z_detector_m=pr.z; if(mi>=0){ const auto& m=p.event[mi]; s.mother_px_GeV=m.px(); s.mother_py_GeV=m.py(); s.mother_pz_GeV=m.pz(); s.mother_E_GeV=m.e(); s.mother_p_GeV=m.pAbs(); s.mother_theta_rad=m.theta(); s.mother_status=m.status(); s.mother_is_primary_like=(m.mother1()==1||m.mother1()==2); int gmi=motherIndex(p.event,mi); s.mother_mother_pdg=(gmi>=0)?p.event[gmi].id():0; s.from_feeddown_flag=(s.mother_mother_pdg!=0); } r.spectra.push_back(s); } } if(o.stopMode==StopMode::FixedEvents && prog->events>=o.nEvents){ prog->stop=true; prog->reason=(int)StopReason::CompletedFixedEvents; } }
    r.stop_reason=(StopReason)prog->reason.load(); prog->done++; return r; }
void writeOutput(const Options& o,const EmitterConfig& e,const std::vector<ThreadResult>& rs,bool open){ std::filesystem::path outPath(o.outFile); if(outPath.has_parent_path()) std::filesystem::create_directories(outPath.parent_path()); TFile f(o.outFile.c_str(),"RECREATE"); if(f.IsZombie()) throw std::runtime_error("Failed to create ROOT output file: "+o.outFile); TTree sum("mcp_summary","MCP emitter summary"); int run_id=o.jobId, thread_id=0, seed=0, emitter_pdg=e.pdg, emitter_type=(int)e.type, production_mode=(int)o.productionMode, geometry_id=(int)o.geometry, is_open=open, stop_reason=0, stopping_mode=(int)o.stopMode, spectra_prescale=o.spectraPrescale; char emitter_name[32], geometry_name_c[32], production_mode_name_c[32], stopping_mode_name[32], spectra_mode_name[32]; snprintf(emitter_name,32,"%s",e.name.c_str()); snprintf(geometry_name_c,32,"%s",geometryName(o.geometry).c_str()); snprintf(production_mode_name_c,32,"%s",productionModeName(o.productionMode).c_str()); snprintf(stopping_mode_name,32,"%s",o.stopMode==StopMode::FixedEvents?"fixed-events":"target-accepted"); snprintf(spectra_mode_name,32,"%s",o.spectraMode==SpectraMode::All?"all":(o.spectraMode==SpectraMode::Accepted?"accepted":"none")); double mcp_mass_GeV=o.mcpMass, emitter_per_event=0, acceptance_fraction=0, acceptance_uncertainty_binomial=0; long long n_events_generated=0,n_pythia_next_failures=0,n_emitter_total=0,n_mcp_total=0,n_mcp_accepted=0,n_mcp_wrong_mother=0,n_mcp_no_mother=0;
#define BR(N,V,L) sum.Branch(N,V,L)
BR("run_id",&run_id,"run_id/I"); BR("job_id",&run_id,"job_id/I"); BR("thread_id",&thread_id,"thread_id/I"); BR("seed",&seed,"seed/I"); BR("mcp_mass_GeV",&mcp_mass_GeV,"mcp_mass_GeV/D"); BR("mcp_mass",&mcp_mass_GeV,"mcp_mass/D"); BR("emitter_pdg",&emitter_pdg,"emitter_pdg/I"); BR("parent_pdg",&emitter_pdg,"parent_pdg/I"); BR("emitter_name",emitter_name,"emitter_name/C"); BR("parent_name",emitter_name,"parent_name/C"); BR("emitter_type",&emitter_type,"emitter_type/I"); BR("parent_type",&emitter_type,"parent_type/I"); BR("production_mode",&production_mode,"production_mode/I"); BR("production_mode_name",production_mode_name_c,"production_mode_name/C"); BR("geometry_id",&geometry_id,"geometry_id/I"); BR("geometry_name",geometry_name_c,"geometry_name/C"); BR("is_kinematically_open",&is_open,"is_kinematically_open/I"); BR("n_events_generated",&n_events_generated,"n_events_generated/L"); BR("n_pythia_next_failures",&n_pythia_next_failures,"n_pythia_next_failures/L"); BR("n_emitter_total",&n_emitter_total,"n_emitter_total/L"); BR("n_parent_total",&n_emitter_total,"n_parent_total/L"); BR("n_mcp_total",&n_mcp_total,"n_mcp_total/L"); BR("n_mcp_accepted",&n_mcp_accepted,"n_mcp_accepted/L"); BR("n_mcp_wrong_mother",&n_mcp_wrong_mother,"n_mcp_wrong_mother/L"); BR("n_mcp_no_mother",&n_mcp_no_mother,"n_mcp_no_mother/L"); BR("emitter_per_event",&emitter_per_event,"emitter_per_event/D"); BR("parent_yield_per_event",&emitter_per_event,"parent_yield_per_event/D"); BR("acceptance_fraction",&acceptance_fraction,"acceptance_fraction/D"); BR("acceptance_uncertainty_binomial",&acceptance_uncertainty_binomial,"acceptance_uncertainty_binomial/D"); BR("stop_reason",&stop_reason,"stop_reason/I"); BR("stopping_mode",&stopping_mode,"stopping_mode/I"); BR("stopping_mode_name",stopping_mode_name,"stopping_mode_name/C"); BR("spectra_mode_name",spectra_mode_name,"spectra_mode_name/C"); BR("spectra_prescale",&spectra_prescale,"spectra_prescale/I");
#undef BR
    if(!open){ stop_reason=(int)StopReason::KinematicallyClosed; seed=o.seed; sum.Fill(); } else { for(const auto& r:rs){ thread_id=r.thread_id; seed=r.seed; n_events_generated=r.n_events_generated; n_pythia_next_failures=r.n_pythia_next_failures; n_emitter_total=r.n_emitter_total; n_mcp_total=r.n_mcp_total; n_mcp_accepted=r.n_mcp_accepted; n_mcp_wrong_mother=r.n_mcp_wrong_mother; n_mcp_no_mother=r.n_mcp_no_mother; emitter_per_event=n_events_generated?double(n_emitter_total)/n_events_generated:0; acceptance_fraction=n_mcp_total?double(n_mcp_accepted)/n_mcp_total:0; acceptance_uncertainty_binomial=n_mcp_total?sqrt(std::max(0.0,acceptance_fraction*(1-acceptance_fraction)/n_mcp_total)):0; stop_reason=(int)r.stop_reason; sum.Fill(); }}
    TTree sp("mcp_spectra","MCP spectra"); SpectraRow s; sp.Branch("event_index",&s.event_index,"event_index/I"); sp.Branch("seed",&s.seed,"seed/I"); sp.Branch("mcp_mass_GeV",&s.mcp_mass_GeV,"mcp_mass_GeV/D"); sp.Branch("emitter_pdg",&s.emitter_pdg,"emitter_pdg/I"); sp.Branch("emitter_type",&s.emitter_type,"emitter_type/I"); sp.Branch("production_mode",&s.production_mode,"production_mode/I"); sp.Branch("geometry_id",&s.geometry_id,"geometry_id/I"); sp.Branch("mcp_pdg",&s.mcp_pdg,"mcp_pdg/I"); sp.Branch("mother_pdg",&s.mother_pdg,"mother_pdg/I"); sp.Branch("mother_index",&s.mother_index,"mother_index/I"); sp.Branch("accepted",&s.accepted,"accepted/I"); sp.Branch("px_GeV",&s.px_GeV,"px_GeV/D"); sp.Branch("py_GeV",&s.py_GeV,"py_GeV/D"); sp.Branch("pz_GeV",&s.pz_GeV,"pz_GeV/D"); sp.Branch("E_GeV",&s.E_GeV,"E_GeV/D"); sp.Branch("p_GeV",&s.p_GeV,"p_GeV/D"); sp.Branch("theta_rad",&s.theta_rad,"theta_rad/D"); sp.Branch("theta_x_rad",&s.theta_x_rad,"theta_x_rad/D"); sp.Branch("theta_y_rad",&s.theta_y_rad,"theta_y_rad/D"); sp.Branch("eta",&s.eta,"eta/D"); sp.Branch("phi_rad",&s.phi_rad,"phi_rad/D"); sp.Branch("x_at_detector_m",&s.x_at_detector_m,"x_at_detector_m/D"); sp.Branch("y_at_detector_m",&s.y_at_detector_m,"y_at_detector_m/D"); sp.Branch("z_detector_m",&s.z_detector_m,"z_detector_m/D"); sp.Branch("passed_geometry",&s.passed_geometry,"passed_geometry/I"); sp.Branch("mother_px_GeV",&s.mother_px_GeV,"mother_px_GeV/D"); sp.Branch("mother_py_GeV",&s.mother_py_GeV,"mother_py_GeV/D"); sp.Branch("mother_pz_GeV",&s.mother_pz_GeV,"mother_pz_GeV/D"); sp.Branch("mother_E_GeV",&s.mother_E_GeV,"mother_E_GeV/D"); sp.Branch("mother_p_GeV",&s.mother_p_GeV,"mother_p_GeV/D"); sp.Branch("mother_theta_rad",&s.mother_theta_rad,"mother_theta_rad/D"); sp.Branch("mother_status",&s.mother_status,"mother_status/I"); sp.Branch("mother_is_primary_like",&s.mother_is_primary_like,"mother_is_primary_like/I"); sp.Branch("mother_mother_pdg",&s.mother_mother_pdg,"mother_mother_pdg/I"); sp.Branch("from_feeddown_flag",&s.from_feeddown_flag,"from_feeddown_flag/I"); for(const auto& r:rs) for(const auto& row:r.spectra){ s=row; sp.Fill(); } sum.Write(); sp.Write(); f.Close(); }
void usage(const char* a){ std::cout<<"Usage: "<<a<<" <seed> <nThreads> <nEventsOrTarget> <mcpMassGeV> <geometry> <emitterName> <productionMode> <outputFile> [--mode fixed-events|target-accepted] [--n-events N] [--n-accepted N] [--max-events N] [--write-spectra all|accepted|none] [--spectra-prescale N] [--beam-config F] [--momentum-config F] [--production-config F] [--print-pythia-settings] [--job-id N] [--quiet|--batch]\n"; }
Options parse(int argc,char**argv){ if(argc<9){usage(argv[0]); throw std::runtime_error("not enough arguments");} Options o; o.seed=std::stoi(argv[1]); o.nThreads=std::stoi(argv[2]); o.legacyN=std::stoll(argv[3]); o.mcpMass=std::stod(argv[4]); o.geometry=parseGeometry(argv[5]); o.emitterName=argv[6]; o.productionMode=parseProductionMode(argv[7]); o.outFile=argv[8]; o.nEvents=o.legacyN; for(int i=9;i<argc;i++){std::string k=argv[i]; auto val=[&](){ if(i+1>=argc) throw std::runtime_error("missing value for "+k); return std::string(argv[++i]);}; if(k=="--mode"){auto v=val(); o.stopMode=(v=="target-accepted")?StopMode::TargetAccepted:StopMode::FixedEvents;} else if(k=="--n-events") o.nEvents=std::stoll(val()); else if(k=="--n-accepted") o.nAccepted=std::stoll(val()); else if(k=="--max-events") o.maxEvents=std::stoll(val()); else if(k=="--write-spectra"){auto v=val(); o.spectraMode=(v=="all")?SpectraMode::All:(v=="none"?SpectraMode::None:SpectraMode::Accepted);} else if(k=="--spectra-prescale") o.spectraPrescale=std::stoi(val()); else if(k=="--beam-config") o.beamConfig=val(); else if(k=="--momentum-config") o.momentumConfig=val(); else if(k=="--production-config") o.productionConfig=val(); else if(k=="--print-pythia-settings") o.printPythiaSettings=true; else if(k=="--job-id") o.jobId=std::stoi(val()); else if(k=="--quiet"||k=="--batch") o.quiet=true; else throw std::runtime_error("unknown option "+k);} if(o.stopMode==StopMode::TargetAccepted){ if(o.nAccepted<0) o.nAccepted=o.legacyN; if(o.maxEvents<0) o.maxEvents=o.nEvents*o.nThreads; } if(o.nThreads<=0||o.mcpMass<=0||o.spectraPrescale<=0) throw std::runtime_error("invalid positive argument"); return o; }
}
int main(int argc,char**argv){ try{ Options o=parse(argc,argv); const EmitterConfig* ep=findEmitter(o.emitterName); if(!ep) throw std::runtime_error("Unknown emitter "+o.emitterName); const EmitterConfig& e=*ep; if(e.production_mode!=o.productionMode) std::cerr<<"WARNING: requested production mode "<<productionModeName(o.productionMode)<<" differs from default for "<<e.name<<" ("<<productionModeName(e.production_mode)<<").\n"; bool open=isKinematicallyOpen(e,o.mcpMass); if(!o.quiet){ std::cout<<"Emitter "<<e.name<<" PDG="<<e.pdg<<" mode="<<productionModeName(o.productionMode)<<" m_parent="<<e.mass_GeV<<" m_chi="<<o.mcpMass<<" open="<<open<<"\n"; } if(!open){ writeOutput(o,e,{},false); std::cout<<"Kinematically closed; wrote zero-summary row to "<<o.outFile<<"\n"; return 0; } Progress prog; prog.reason=(int)StopReason::CompletedFixedEvents; std::vector<std::thread> th; std::vector<ThreadResult> rs(o.nThreads); long long perThread=(o.stopMode==StopMode::FixedEvents)?((o.nEvents+o.nThreads-1)/o.nThreads):0; for(int i=0;i<o.nThreads;i++) th.emplace_back([&,i](){rs[i]=runThread(o,e,i,perThread,&prog);}); while(!o.quiet && prog.done<o.nThreads){ std::cout<<"\r events="<<prog.events<<" accepted="<<prog.accepted<<" failures="<<prog.failures<<" done="<<prog.done<<"/"<<o.nThreads<<std::flush; std::this_thread::sleep_for(std::chrono::milliseconds(500)); } for(auto& t:th)t.join(); if(!o.quiet) std::cout<<"\n"; writeOutput(o,e,rs,true); long long ev=0,em=0,mc=0,ac=0,wm=0,nm=0,nf=0; StopReason sr=StopReason::CompletedFixedEvents; for(auto&r:rs){ev+=r.n_events_generated; em+=r.n_emitter_total; mc+=r.n_mcp_total; ac+=r.n_mcp_accepted; wm+=r.n_mcp_wrong_mother; nm+=r.n_mcp_no_mother; nf+=r.n_pythia_next_failures; sr=r.stop_reason;} double emitterPerEvent=ev?double(em)/ev:0.0; std::cout<<"Final summary:\n"<<"events="<<ev<<"\n"<<"emitter_total="<<em<<"\n"<<"emitter_per_event="<<emitterPerEvent<<"\n"<<"mcp="<<mc<<"\n"<<"accepted="<<ac<<"\n"<<"wrong_mother="<<wm<<"\n"<<"no_mother="<<nm<<"\n"<<"pythia_next_failures="<<nf<<"\n"<<"stop_reason="<<stopReasonName(sr)<<"\n"<<"production_mode="<<productionModeName(o.productionMode)<<"\n"<<"output="<<o.outFile<<"\n"; return 0; } catch(const std::exception& ex){ std::cerr<<"ERROR: "<<ex.what()<<"\n"; return 2; } }
